#!/usr/bin/env bash

#Requirements
# openssl
# oathtool
# qrencode


OATHKEYFILE=${OATHKEYFILE:-~/.oathKeys}

usage() {
    (>&2 echo "Usage: $0 [-a <SERVICE>  <KEY> | -c <SERVICE>  <KEY> [-q] | -l  [SERVICE] [-q] | -s |-h]")
    (>&2 echo "   -a -- Adds new entry")
    (>&2 echo "   -c -- Calculate entry")
    (>&2 echo "   -l -- list codes of added services")
    (>&2 echo "   -s -- change salt string")
    (>&2 echo "   -q -- print qrcode ")
    (>&2 echo "   -t -- test dependencies")
    exit -1
}
testDependencies() {
    hash openssl 2>/dev/null || { echo >&2 "openssl is require but it's not installed.  Aborting."; exit 1; }
    hash oathtool 2>/dev/null || { echo >&2 "oathtool is require but it's not installed.  Aborting."; exit 1; }
    hash qrencode 2>/dev/null || { echo >&2 "qrencode is require but it's not installed.  Aborting."; exit 1; }
}

encrypt() {
    echo "$1" | openssl enc -aes-128-cbc -a -salt -pass pass:$2 | tr -d "\n"
}

decrypt() {
    echo "$1" | openssl enc -aes-128-cbc -a -d -salt -pass pass:$2 openssl 2>/dev/null
}

getsalt() {
    (>&2 echo "Insert ${1} salt: ")
    read -s salt
    echo $salt
}

calculate() {
    service=$1
    key=$2
    if [ -z "$service" ] || [ -z "$key" ]; then
        usage
    fi

    code=`oathtool  --totp -b "${key}"`
    echo "$service: ${code:0:3} ${code:3:6}"
}

validateSalt () {
    salt=$1
    line=$(head -n1 ${OATHKEYFILE})
    if [[ ! -z  $line ]] ; then
        line=$(decrypt "$line" "$salt")
        if [[ $line != *": "* ]] ; then
            echo >&2 "Failed to validate the salt.";
            exit 1
        fi
    fi
}


while getopts "a:c:lqst" flag; do
    case ${flag} in
        a)
            service=$2
            key=$3
            salt=${GSALT:-$(getsalt)}
            testDependencies
            validateSalt $salt
            calculate "$service" "$key"
            salted=$(encrypt "${service}: $key" "$salt")
            echo "Storing service key";
            echo "$salted" >> ${OATHKEYFILE}
            ;;
        c)
            testDependencies
            echo "Calculating code:"
            calculate "$2" "$3"
            ;;
        l)
            filter=$2
            salt=${GSALT:-$(getsalt)}
            validateSalt $salt
            testDependencies
            while read -r line
            do
                line=$(decrypt "$line" "$salt")
                service=$(echo $line | sed -e 's/: .*//')
                key=$(echo $line | sed -e 's/.*: //')
                if [ -z "${filter}" ] ||  echo "$service" | grep -iqF "${filter}" ; then
                    calculate "$service" "$key"
                fi
            done < ${OATHKEYFILE}
            ;;
        q)
            filter=$2
            salt=${GSALT:-$(getsalt)}
            validateSalt $salt
            testDependencies
            while read -r line
            do
                line=$(decrypt "$line" "$salt")
                service=$(echo $line | sed -e 's/: .*//')
                key=$(echo $line | sed -e 's/.*: //')
                if [ -z "${filter}" ] ||  echo "$service" | grep -iqF "${filter}" ; then
                    tempFile=$(mktemp oath.XXX)
                     qrencode -t ANSIUTF8 -o $tempFile\
                        "otpauth://totp/${service}?secret=${key}&issuer="
                    if [[ -f $tempFile ]] ; then
                        echo -e "\n$service"
                        cat  $tempFile
                        rm $tempFile
                    else
                        echo >&2 "Failed to generate qrcode.";
                        exit 1;
                    fi
                fi
            done < ${OATHKEYFILE}
            ;;
        s)
            testDependencies
            oldsalt=$(getsalt old)
            validateSalt $salt
            newsalt=$(getsalt new)
            while read -r line
            do
                tempFile=$(mktemp oath.XXX)
                line=$(decrypt "$line" "$oldsalt")
                encrypt "$line" "$newsalt" >> $tempFile
                echo "" >> $tempFile
            done < ${OATHKEYFILE}
            cp $tempFile ${OATHKEYFILE}
            rm $tempFile
            ;;
        t)
            echo >&2 "Checking for dependencies..."
            testDependencies verbose
            echo >&2 "Done."
            ;;
        *)
            usage
            ;;
    esac
done
